In [1]:
import torch

In [2]:
x = torch.tensor(3.0, requires_grad=True)

In [3]:
y = x**2

x,y

(tensor(3., requires_grad=True), tensor(9., grad_fn=<PowBackward0>))

In [4]:
y.backward()

In [5]:
x.grad

tensor(6.)

In [6]:
x = torch.tensor(4.0, requires_grad=True)

In [7]:
y = x ** 2

In [8]:
z = torch.sin(y)

In [9]:
x

tensor(4., requires_grad=True)

In [10]:
y

tensor(16., grad_fn=<PowBackward0>)

In [11]:
z

tensor(-0.2879, grad_fn=<SinBackward0>)

In [12]:
z.backward()

In [13]:
y.grad

C:\Users\gamer\AppData\Local\Temp\ipykernel_24240\486760323.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\build\aten\src\ATen/core/TensorBody.h:494.)
  y.grad


In [14]:
x.grad

tensor(-7.6613)

In [15]:
y.grad

C:\Users\gamer\AppData\Local\Temp\ipykernel_24240\486760323.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\build\aten\src\ATen/core/TensorBody.h:494.)
  y.grad


In [16]:
x = torch.tensor(6.7)
y = torch.tensor(0.0)

w = torch.tensor(1.0)
b = torch.tensor(0.0)


In [17]:
def binary_cross_entropy_loss (prediction, target):
    epsilon = 1e-8
    prediction = torch.clamp(prediction, epsilon, 1- epsilon)
    return -(target*torch.log(prediction) + (1-target) * torch.log(1-prediction))

In [18]:
z = w*x + b #Weighted Sum
y_pred = torch.sigmoid(z)


loss = binary_cross_entropy_loss(y_pred, y)

In [19]:
loss

tensor(6.7012)

In [22]:
dloss_dy_pred = (y_pred - y) / (y_pred*(1-y_pred))


dy_pred_dz = y_pred * (1- y_pred)

dz_dw = x
dz_db = 1

dL_dw = dloss_dy_pred * dy_pred_dz * dz_dw

dL_db = dloss_dy_pred * dy_pred_dz * dz_db

In [25]:
dL_dw.item(), dL_db.item()

(6.691762447357178, 0.998770534992218)

In [26]:
#Using Autograd to simplify this whole task

In [27]:
x = torch.tensor(6.7)
y = torch.tensor(0.0)

In [28]:
w = torch.tensor(1.0, requires_grad=True)
b = torch.tensor(0.0, requires_grad=True)

In [30]:
z = w * x + b
z

tensor(6.7000, grad_fn=<AddBackward0>)

In [31]:
y_pred = torch.sigmoid(z)

In [32]:
loss = binary_cross_entropy_loss(y_pred,y)
loss

tensor(6.7012, grad_fn=<NegBackward0>)

In [35]:
loss.backward()

In [36]:
w.grad

tensor(6.6918)

In [37]:
b.grad

tensor(0.9988)

In [39]:
x = torch.tensor([1.0,2.0,3.0],requires_grad=True)
x

tensor([1., 2., 3.], requires_grad=True)

In [52]:
y = (x**2).mean()
y

tensor(4.6667, grad_fn=<MeanBackward0>)

In [53]:
y.backward()

In [54]:
x.grad

tensor([0.6667, 1.3333, 2.0000])

In [55]:
#Clearing Grad

#Gradients start accumulating as you continuously do backward pass, hence all the gradients get added up. To prevent this we clear Gradients
x.grad.zero_()


tensor([0., 0., 0.])