In [1]:
import torch

C:\Users\Shubham\anaconda3\Lib\site-packages\torch\utils\_pytree.py:185: FutureWarning: optree is installed but the version is too old to support PyTorch Dynamo in C++ pytree. C++ pytree support is disabled. Please consider upgrading optree using `python3 -m pip install --upgrade 'optree>=0.13.0'`.
  warnings.warn(


In [3]:
if torch.cuda.is_available():
    print("GPU Available")
else:
    print("GPU not Available. Using CPU")

GPU not Available. Using CPU


## Creating a Tensor

In [27]:
# USing empty
#Empty function allocates the space for tensor in memory, however it dosen't allocate any values to tensor at start,
#The values we see after creating a tensor are the values which are present at that memory location
tensor = torch.empty((2,2))
tensor

tensor([[ 5.0000, 18.9802],
        [ 0.0000,  0.0000]])

In [28]:
#Check type

type(tensor)

torch.Tensor

In [35]:
#Using Zeros

torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [36]:
#Using Ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [37]:
#USing rand
#Values are selected randomly BETWEEN 0 TO 1
torch.rand(2,3)

tensor([[0.9360, 0.4532, 0.8681],
        [0.1319, 0.0509, 0.8620]])

In [41]:
#manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [42]:
#Using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [46]:
#Arange

torch.arange(0,10) #Tensor with all integers between 0 to 10

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
#linspace

torch.linspace(0,10,10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [55]:
#Eye

torch.eye(3) #Itentity matrix of given shape

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [57]:
#using full

torch.full((3,3),5) #3x3 tensor with 5 only

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

## Tensor Shapes

In [58]:
tensor.shape

torch.Size([2, 2])

In [66]:
torch.empty_like(tensor)

tensor([[1.9359e+25, 1.4335e-42],
        [0.0000e+00, 1.0000e+00]])

In [67]:
torch.zeros_like(tensor)

tensor([[0., 0.],
        [0., 0.]])

In [91]:
torch.rand_like(tensor, dtype=torch.float32)

tensor([[0.4450, 0.7278],
        [0.4563, 0.3389]])

## Tensor Data Types

In [81]:
#Find datatype
tensor.dtype

torch.float32

In [84]:
#Assign datatype
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [85]:
torch.tensor([1,2,3],dtype=torch.float32)

tensor([1., 2., 3.])

In [86]:
#USing to()

tensor.to(torch.int)

tensor([[ 5, 18],
        [ 0,  0]], dtype=torch.int32)

## Mathematical Operation

In [99]:
x = torch.rand(2,2)
x

tensor([[0.3271, 0.0103],
        [0.9516, 0.2855]])

In [108]:
#Addition 
x + 2

#Subtraction
x - 2

#Multiplication
x*3

#Division
x / 3

# int division
x//3

#Mod
x%2

#power
x**2

tensor([[1.0699e-01, 1.0516e-04],
        [9.0555e-01, 8.1525e-02]])

In [109]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.2324, 0.9141, 0.7668],
        [0.1659, 0.4393, 0.2243]])
tensor([[0.8935, 0.0497, 0.1780],
        [0.3011, 0.1893, 0.9186]])


In [112]:
# Add
a+b

# sub
a-b

# multiply
a*b

# division
a/b

# power
a**b

# mod
a%b

tensor([[0.2324, 0.0187, 0.0549],
        [0.1659, 0.0607, 0.2243]])

In [113]:
c = torch.tensor([-1,2,-3,4])

In [114]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [116]:
#negative
torch.neg(c)

tensor([ 1, -2,  3, -4])

In [117]:
#round
torch.round(x)

tensor([[0., 0.],
        [1., 0.]])

In [119]:
#ceil
torch.ceil(tensor)

tensor([[ 5., 19.],
        [ 0.,  0.]])

In [120]:
#floor
torch.floor(tensor)

tensor([[ 5., 18.],
        [ 0.,  0.]])

In [129]:
#clamp
d = torch.tensor([1.9,2.3,3.7,4.4])
torch.clamp(d,2,3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

## Reduction Operation

In [131]:
e = torch.randint(size=(2,3),low=0,high=10)
e

tensor([[7, 2, 5],
        [6, 1, 4]])

In [139]:
#Sum
e.sum()

#Sum along columns
e.sum(dim=0)

#SUm along rows
e.sum(dim=1)

tensor([14, 11])

In [147]:
#mean
e.mean(dtype=torch.float32)

tensor(4.1667)

In [148]:
#Median
e.median()

tensor(4)

In [149]:
#Max and min
e.max(),e.min()

(tensor(7), tensor(1))

In [150]:
#product
e.prod()

tensor(1680)

In [161]:
#Standard Deviation
torch.std(tensor)

tensor(8.9719)

In [163]:
#variance
torch.var(tensor)

tensor(80.4954)

In [167]:
#Argmax

torch.argmax(e)

tensor(0)

In [171]:
#Argmin

torch.argmin(e)

tensor(4)

## Matrix Operations

In [181]:
f = torch.randint(size=(2,3),low=0,high=10)
g = torch.randint(size=(3,2),low=0,high=10)

f,g

torch.matmul(f,g)

tensor([[10,  2],
        [34,  6]])

In [180]:
#Matrix multiplication
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])


torch.matmul(vector1, vector2)

tensor(11)

In [183]:
#Transpose
torch.transpose(f,0,1)

tensor([[0, 4],
        [2, 6],
        [4, 2]])

In [186]:
f = torch.randint(size=(2,3,3),low=0,high=10)
f

tensor([[[3, 6, 7],
         [8, 1, 2],
         [3, 2, 7]],

        [[9, 3, 9],
         [7, 7, 5],
         [9, 2, 2]]])

In [188]:
torch.transpose(f,1,0)

tensor([[[3, 6, 7],
         [9, 3, 9]],

        [[8, 1, 2],
         [7, 7, 5]],

        [[3, 2, 7],
         [9, 2, 2]]])

In [189]:
f

tensor([[[3, 6, 7],
         [8, 1, 2],
         [3, 2, 7]],

        [[9, 3, 9],
         [7, 7, 5],
         [9, 2, 2]]])

In [192]:
#Determinant
torch.det(tensor)

tensor(-0.)

In [193]:
#inverse
torch.inverse(tensor)

_LinAlgError: linalg.inv: The diagonal element 2 is zero, the inversion could not be completed because the input matrix is singular.

In [194]:
tensor

tensor([[ 5.0000, 18.9802],
        [ 0.0000,  0.0000]])

In [195]:
#log 
torch.log(tensor)

tensor([[1.6094, 2.9434],
        [  -inf,   -inf]])

In [196]:
#exp
tensor.exp()

tensor([[1.4841e+02, 1.7499e+08],
        [1.0000e+00, 1.0000e+00]])

In [197]:
# sqrt
tensor.sqrt()

tensor([[2.2361, 4.3566],
        [0.0000, 0.0000]])

In [198]:
# sigmoid
tensor.sigmoid()

tensor([[0.9933, 1.0000],
        [0.5000, 0.5000]])

In [201]:
# Softmax
tensor.softmax(dim=1)

tensor([[8.4813e-07, 1.0000e+00],
        [5.0000e-01, 5.0000e-01]])

In [203]:
# relu
tensor.relu()

tensor([[ 5.0000, 18.9802],
        [ 0.0000,  0.0000]])

In [246]:
a.add_(b)

tensor([[  14.0873, 7831.2026,  170.0726],
        [  21.3239,   95.3242,   14.3348]])

In [247]:
a

tensor([[  14.0873, 7831.2026,  170.0726],
        [  21.3239,   95.3242,   14.3348]])

In [248]:
a.sigmoid_()
a

tensor([[1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000]])

In [250]:
#COpying a Tensor

b = a.clone()

In [252]:
a.add_(5)

tensor([[6.0000, 6.0000, 6.0000],
        [6.0000, 6.0000, 6.0000]])

In [254]:
b

tensor([[1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000]])

In [255]:
id(a)

3077386286192

In [256]:
id(b)

3077392273712

In [262]:
device=torch.device("cuda") if torch.cuda.is_available() else "cpu"

In [263]:
#Creating a new tensor on GPU

torch.rand((2,3),device=device)

tensor([[0.9792, 0.4947, 0.3617],
        [0.9687, 0.0359, 0.3041]])

In [265]:
#Moving existing tensor to a GPU
a.to(device)

tensor([[6.0000, 6.0000, 6.0000],
        [6.0000, 6.0000, 6.0000]])

## Reshaping Tensors

In [274]:
#reshape
a.reshape((3,2))

tensor([[6.0000, 6.0000],
        [6.0000, 6.0000],
        [6.0000, 6.0000]])

In [275]:
#Flatten
a.flatten()

tensor([6.0000, 6.0000, 6.0000, 6.0000, 6.0000, 6.0000])

In [277]:
b = torch.rand(2,3,4)

In [283]:
#permute
b.permute(2,1,0)

tensor([[[0.9867, 0.2420],
         [0.0899, 0.2440],
         [0.2316, 0.6201]],

        [[0.1290, 0.4928],
         [0.3139, 0.8994],
         [0.2847, 0.3658]],

        [[0.6887, 0.5772],
         [0.1219, 0.1041],
         [0.3520, 0.0623]],

        [[0.1637, 0.3771],
         [0.3516, 0.9193],
         [0.2828, 0.5967]]])

In [293]:
# unsqueeze
c = torch.rand(226,226,3)
print(c.shape)
c = c.unsqueeze(dim=0)
print(c.shape)

torch.Size([226, 226, 3])
torch.Size([1, 226, 226, 3])


In [301]:
# squeeze

c.squeeze().shape

torch.Size([226, 226, 3])